set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

set(VCPKG_FIXUP_ELF_RPATH ON)

if(PORT MATCHES "gstreamer")
  set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()

if(PORT MATCHES "glib")
  set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()
set(VCPKG_CUDA_VERSION "12.6")
